services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - "./rules.yml:/etc/prometheus/rules.yml"
      - "prometheus_data:/prometheus"
    networks:
      - localprom
      - traefik
    ports:
      - "9090:9090"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.pdm.musubi.dev`)"
      - "traefik.http.routers.prometheus.entrypoints=websecure"
      - "traefik.http.routers.prometheus.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.docker.network=traefik"
      # WatchTower auto update
      # TODO: Check for non interrupting update
      - "com.centurylinklabs.watchtower.enable=true"
    restart: unless-stopped

  node-exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
      - '--collector.hwmon'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - localprom

    
networks:
  localprom:
    driver: bridge
  traefik:
    external: true

volumes:
  prometheus_data: