global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml
alerting:
  alertmanagers:
   - static_configs:
     - targets:
        - alert-manager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter-docker'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'node-exporter-web'
    static_configs:
      - targets: ['10.0.0.4:9100']

#  - job_name: 'node-exporter-db'
#    static_configs:
#      - targets: ['10.0.0.6:9100']

  - job_name: 'app'
    scheme: https
    static_configs:
      - targets: ['app.pdm.musubi.dev:443']

  - job_name: 'postgres'
    static_configs:
      - targets: ['10.0.0.4:9187']