services:
  grafana:
    container_name: grafana
    image: grafana/grafana-oss:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
    - GF_SERVER_ROOT_URL=https://grafana.pdm.musubi.dev
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.grafana.entrypoints=websecure"
    - "traefik.http.routers.grafana.tls.certresolver=letsencryptresolver"
    - "traefik.http.routers.grafana.tls=true"
    - "traefik.http.routers.grafana.rule=Host(`grafana.pdm.musubi.dev`)"
    - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    - "traefik.docker.network=traefik"
    volumes:
      - ./datasources:/etc/grafana/provisioning/datasources
      - grafana-storage:/var/lib/grafana
    # env_file:
    #   - .env.conf
    networks:
      - traefik
      - default

  loki:
    image: grafana/loki:latest
    container_name: loki
    user: "0:0"
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - default
      # - traefik

volumes:
  grafana-storage:
  loki-data:

networks:
  traefik:
    external: true