{
 "title": "Sample app",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Goroutines count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"app.pdm.musubi.dev:443\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{instance=\"app.pdm.musubi.dev:443\"}",
     "legendFormat": "sample app"
    }
   ]
  },
  {
   "title": "Request duration per page",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[$__rate_interval])",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}